### ISSUE TITLE
test with userPrivateKeyFile

### ISSUE THREAD

**Issue by overag3** [speatzle/go-passbolt-cli#3]
Are you sure this if statement in line 100 is right ?
https://github.com/speatzle/go-passbolt-cli/blob/0449e9983cd98c7a946a901770bcc50fa50c8633/cmd/root.go#L100-L105

If no error raised and option userPrivateKeyFile isn't empty, the contents of the PrivateKeyFile is never saved in config file.

**Comment by speatzle** [comment]
This if statement checks first that there was no error reading the flag and second that the user Provided a KeyFile Path (that it is not empty).
If that is the case then the UserPrivateKey gets replaced with the contents of the file at UserPrivateKeyPath.

This Piece of Code is only there to replace the UserPrivateKey with the file contents of UserPrivateKeyPath if UserPrivateKeyPath is set.

**Comment by speatzle** [comment]
Ah i see the problem now, thank you. This did work in my test anyway so ill need to look into this.

**Comment by speatzle** [comment]
fixed with release v0.1.6

**Comment by overag3** [comment]
Many thanks, i appreciate your work ! 😉
