### ISSUE TITLE
Getting error "UUID is not in the valid format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" when trying to retrieve a resource by ID

### ISSUE THREAD

**Issue by marius-locomotion** [speatzle/go-passbolt-cli#6]
Hello,

I am getting the error below, when trying to retrieve a resource by ID.
Do you have any idea, is this related to the Passbolt instance version (maybe we need to update it), or it's something related to the CLI tool?

Interestingly enough, the command `passbolt get user --id` works as expected

thanks a lot,
Marius

`/ # passbolt get resource --id 30496b73-ab1e-4ee7-b63b-1b44facb8a3e
Error: Getting Resource: Getting ResourceType: Checking ID format: UUID is not in the valid format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
/ # 
`

**Comment by speatzle** [comment]
Hi,

I will look at this later, this is a new security check since v0.5.3 indicating that the resource types id is not correctly formatted. As a temporary fix, you can downgrade to [v0.5.2](https://github.com/speatzle/go-passbolt/releases/tag/v0.5.2)

**Comment by marius-locomotion** [comment]
but I am passing the correct ID.. exactly as I am getting from the API when I do `list resources`
I'm guessing this was a bug in the passbolt API which was fixed since (our instance is one year old).. We will try upgrading the instance and see if the issue still occurs

**Comment by speatzle** [comment]
Ah, an old passbolt instance version would do it, the ResourceTypes didn't exist in old versions (defines if the password has an encrypted description or not and more in the future). The CLI Relies on this information to Correctly Encrypt and Decrypt Passwords.

**Comment by marius-locomotion** [comment]
quick update, we resolved this by updating passbolt instance to latest version (3.5.0). It works as expected now, thanks!
